name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Setup node.js
        uses: actions/setup-node@main
        with:
          node-version: 'lts/Fermium'

      - name: Install packages
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ github.token }}
          branch: gh-pages
          folder: .vuepress/dist
